// : Generated by xaf-index-generator :

export { default as TemplateDefault } from './template.default.vue'
export { default as TemplateEmpty } from './template.empty.vue'
export { default as TemplateFullscreen } from './template.fullscreen.vue'