start:
	docker-compose -f docker-compose.yaml up --build
start-d:
	docker-compose -f docker-compose.yaml -d up --build
stop:
	docker-compose -f docker-compose.yaml stop
logs:
	docker-compose -f docker-compose.yaml logs -f
kill:
	docker-compose -f docker-compose.yaml kill
container:
	docker container -f docker-compose.yaml ls -a
