version: "3.9"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - "./app:/usr/src/app"
      - "./app/static:/usr/src/app/static"
    restart: on-failure
    ports:
      - "8000:8000"

  db:
    restart: always
    image: postgres:14.2-alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db:
